using System.Collections.Generic;

namespace FileExplorer.Services;

/// <summary>Catalogo EN delle stringhe UI. Chiavi mirror di <see cref="StringsIt"/>.</summary>
public static class StringsEn
{
    public static readonly IReadOnlyDictionary<string, string> All = new Dictionary<string, string>
    {
        ["Str.Common.Cancel"] = "Cancel",
        ["Str.Common.Ok"] = "OK",
        ["Str.Common.Save"] = "Save",
        ["Str.Common.Delete"] = "Delete",
        ["Str.Common.Name"] = "Name",
        ["Str.Common.Size"] = "Size",
        ["Str.Common.Modified"] = "Last modified",
        ["Str.Common.Ready"] = "Ready",
        ["Str.Common.Cancelled"] = "Cancelled",
        ["Str.Common.ErrorFormat"] = "Error: {0}",
        ["Str.Common.Browse"] = "Browse",
        ["Str.Common.Analyze"] = "Analyze",
        ["Str.Common.Analyzing"] = "Analyzing…",
        ["Str.Common.SelectValidFolder"] = "Select a valid folder",
        ["Str.Common.AnalyzeFolderWatermark"] = "Folder to analyze…",
        ["Str.InputDialog.Watermark"] = "Name…",
        ["Str.PathPicker.Go"] = "Go",
        ["Str.PathPicker.Select"] = "Select",
        ["Str.SelectPathDialog.Title"] = "Select file or folder",
        ["Str.SelectPathDialog.UncNotSupported"] = "UNC path not supported on this system: mount the network share and use the mount point.",
        ["Str.Settings.Language"] = "Language",
        ["Str.Settings.LanguageItalian"] = "Italiano",
        ["Str.Settings.LanguageEnglish"] = "English",
        ["Str.Nav.Copy"] = "Copy",
        ["Str.Nav.Remote"] = "Remote server",
        ["Str.Nav.Compare"] = "Compare",
        ["Str.Nav.WatchSync"] = "Auto sync",
        ["Str.Nav.Duplicates"] = "Duplicates",
        ["Str.Nav.DiskUsage"] = "Disk usage",
        ["Str.Nav.Settings"] = "Settings",
        ["Str.Nav.ToggleMenu"] = "Expand/collapse menu",
        ["Str.CopyPairs.ThrottleTooltip"] = "Limit copy speed",
        ["Str.CopyPairs.AddPair"] = "Add pair",
        ["Str.CopyPairs.ProfileLabel"] = "Profile:",
        ["Str.CopyPairs.NoProfile"] = "No profile",
        ["Str.CopyPairs.SaveProfileTooltip"] = "Save current pairs as profile",
        ["Str.CopyPairs.ApplyProfileTooltip"] = "Apply selected profile",
        ["Str.CopyPairs.DeleteProfileTooltip"] = "Delete selected profile",
        ["Str.CopyPairs.EmptyTitle"] = "No copy pairs",
        ["Str.CopyPairs.AddFirstPair"] = "Add first pair",
        ["Str.CopyPairs.SourceWatermark"] = "Source…",
        ["Str.CopyPairs.DestinationWatermark"] = "Destination…",
        ["Str.CopyPairs.AddDestination"] = "Add destination",
        ["Str.CopyPairs.SimulateTooltip"] = "Simulate (dry run): nothing is written",
        ["Str.CopyPairs.Start"] = "Start",
        ["Str.CopyPairs.ShowFiles"] = "Show files to process",
        ["Str.CopyPairs.Interrupted"] = "Interrupted — press Start to resume",
        ["Str.CopyPairs.SaveProfileTitle"] = "Save profile",
        ["Str.CopyPairs.SaveProfileMessage"] = "Copy profile name:",
        ["Str.CopyPairs.DeleteProfileTitle"] = "Delete profile",
        ["Str.CopyPairs.DeleteProfileMessageFormat"] = "Delete profile \"{0}\"?",
        ["Str.CopyPairs.InvalidPaths"] = "Invalid paths",
        ["Str.CopyPairs.CopyInProgress"] = "Copy in progress…",
        ["Str.CopyPairs.Simulating"] = "Simulating…",
        ["Str.CopyPairs.SimulateToCopyFormat"] = "To copy: {0} files, {1}",
        ["Str.CopyPairs.SimulateSkippedFormat"] = " ({0} unchanged, skipped)",
        ["Str.CopyPairs.FreeSpaceUnknown"] = "free space unknown",
        ["Str.CopyPairs.FreeSpaceFormat"] = "{0} free",
        ["Str.CopyPairs.NotEnoughSpace"] = " — NOT ENOUGH SPACE",
        ["Str.CopyPairs.OverwriteLineFormat"] = "{0}: {1} overwrites, {2}",
        ["Str.CopyPairs.SimulateNotEnoughSpace"] = "Simulation: not enough space",
        ["Str.CopyPairs.SimulateComplete"] = "Simulation complete",
        ["Str.CopyPairs.SimulateErrorFormat"] = "Simulation error: {0}",
        ["Str.CopyPairs.Completed"] = "Completed",
        ["Str.CopyPairs.VerifyingChecksum"] = "Verifying checksum…",
        ["Str.CopyPairs.CompletedChecksumMismatch"] = "Completed (checksum mismatch)",
        ["Str.CopyPairs.VerifyingChecksumProgressFormat"] = "Verifying checksum… ({0}/{1})",
        ["Str.CopyPairs.CompletedVerifiedFormat"] = "Completed and verified ({0} files)",
        ["Str.CopyPairs.VerifyFailedFormat"] = "Verification failed: {0} different files, {1} missing",
        ["Str.CopyPairs.NoFilesToCopy"] = "No files to copy",
        ["Str.CopyPairs.CopyingFolderFormat"] = "Copying folder… ({0} files)",
    };
}
