using System.Collections.Generic;

namespace FileExplorer.Services;

/// <summary>
/// Catalogo IT delle stringhe UI — lingua di fallback. L'insieme delle chiavi deve
/// combaciare esattamente con <see cref="StringsEn"/> (verificato da
/// LocalizationServiceTests.StringsEn_has_same_keys_as_StringsIt).
/// </summary>
public static class StringsIt
{
    public static readonly IReadOnlyDictionary<string, string> All = new Dictionary<string, string>
    {
        ["Str.Common.Cancel"] = "Annulla",
        ["Str.Common.Ok"] = "OK",
        ["Str.Common.Save"] = "Salva",
        ["Str.Common.Delete"] = "Elimina",
        ["Str.Common.Name"] = "Nome",
        ["Str.Common.Size"] = "Dimensione",
        ["Str.Common.Modified"] = "Ultima modifica",
        ["Str.Common.Ready"] = "Pronto",
        ["Str.Common.Cancelled"] = "Annullato",
        ["Str.Common.ErrorFormat"] = "Errore: {0}",
        ["Str.Common.Browse"] = "Sfoglia",
        ["Str.Common.Analyze"] = "Analizza",
        ["Str.Common.Analyzing"] = "Analisi…",
        ["Str.Common.SelectValidFolder"] = "Selezionare una cartella valida",
        ["Str.Common.AnalyzeFolderWatermark"] = "Cartella da analizzare…",
        ["Str.InputDialog.Watermark"] = "Nome…",
        ["Str.PathPicker.Go"] = "Vai",
        ["Str.PathPicker.Select"] = "Seleziona",
        ["Str.SelectPathDialog.Title"] = "Seleziona file o cartella",
        ["Str.SelectPathDialog.UncNotSupported"] = "Percorso UNC non supportato su questo sistema: montare la condivisione di rete e usare il punto di mount.",
        ["Str.Settings.Language"] = "Lingua",
        ["Str.Settings.LanguageItalian"] = "Italiano",
        ["Str.Settings.LanguageEnglish"] = "English",
        ["Str.Nav.Copy"] = "Copia",
        ["Str.Nav.Remote"] = "Server remoto",
        ["Str.Nav.Compare"] = "Confronto",
        ["Str.Nav.WatchSync"] = "Sync auto",
        ["Str.Nav.Duplicates"] = "Duplicati",
        ["Str.Nav.DiskUsage"] = "Spazio disco",
        ["Str.Nav.Settings"] = "Impostazioni",
        ["Str.Nav.ToggleMenu"] = "Espandi/comprimi menu",
        ["Str.CopyPairs.ThrottleTooltip"] = "Limita velocità di copia",
        ["Str.CopyPairs.AddPair"] = "Aggiungi coppia",
        ["Str.CopyPairs.ProfileLabel"] = "Profilo:",
        ["Str.CopyPairs.NoProfile"] = "Nessun profilo",
        ["Str.CopyPairs.SaveProfileTooltip"] = "Salva le coppie correnti come profilo",
        ["Str.CopyPairs.ApplyProfileTooltip"] = "Applica il profilo selezionato",
        ["Str.CopyPairs.DeleteProfileTooltip"] = "Elimina il profilo selezionato",
        ["Str.CopyPairs.EmptyTitle"] = "Nessuna coppia di copia",
        ["Str.CopyPairs.AddFirstPair"] = "Aggiungi la prima coppia",
        ["Str.CopyPairs.SourceWatermark"] = "Sorgente…",
        ["Str.CopyPairs.DestinationWatermark"] = "Destinazione…",
        ["Str.CopyPairs.AddDestination"] = "Aggiungi destinazione",
        ["Str.CopyPairs.SimulateTooltip"] = "Simula (dry-run): niente viene scritto",
        ["Str.CopyPairs.Start"] = "Avvia",
        ["Str.CopyPairs.ShowFiles"] = "Mostra file da elaborare",
        ["Str.CopyPairs.Interrupted"] = "Interrotto — premere Avvia per riprendere",
        ["Str.CopyPairs.SaveProfileTitle"] = "Salva profilo",
        ["Str.CopyPairs.SaveProfileMessage"] = "Nome del profilo di copia:",
        ["Str.CopyPairs.DeleteProfileTitle"] = "Elimina profilo",
        ["Str.CopyPairs.DeleteProfileMessageFormat"] = "Eliminare il profilo \"{0}\"?",
        ["Str.CopyPairs.InvalidPaths"] = "Percorsi non validi",
        ["Str.CopyPairs.CopyInProgress"] = "Copia in corso…",
        ["Str.CopyPairs.Simulating"] = "Simulazione…",
        ["Str.CopyPairs.SimulateToCopyFormat"] = "Da copiare: {0} file, {1}",
        ["Str.CopyPairs.SimulateSkippedFormat"] = " (di cui {0} invariati, saltati)",
        ["Str.CopyPairs.FreeSpaceUnknown"] = "spazio libero sconosciuto",
        ["Str.CopyPairs.FreeSpaceFormat"] = "liberi {0}",
        ["Str.CopyPairs.NotEnoughSpace"] = " — SPAZIO INSUFFICIENTE",
        ["Str.CopyPairs.OverwriteLineFormat"] = "{0}: {1} sovrascritture, {2}",
        ["Str.CopyPairs.SimulateNotEnoughSpace"] = "Simulazione: spazio insufficiente",
        ["Str.CopyPairs.SimulateComplete"] = "Simulazione completata",
        ["Str.CopyPairs.SimulateErrorFormat"] = "Errore simulazione: {0}",
        ["Str.CopyPairs.Completed"] = "Completato",
        ["Str.CopyPairs.VerifyingChecksum"] = "Verifica checksum…",
        ["Str.CopyPairs.CompletedChecksumMismatch"] = "Completato (checksum non corrisponde)",
        ["Str.CopyPairs.VerifyingChecksumProgressFormat"] = "Verifica checksum… ({0}/{1})",
        ["Str.CopyPairs.CompletedVerifiedFormat"] = "Completato e verificato ({0} file)",
        ["Str.CopyPairs.VerifyFailedFormat"] = "Verifica fallita: {0} file diversi, {1} mancanti",
        ["Str.CopyPairs.NoFilesToCopy"] = "Nessun file da copiare",
        ["Str.CopyPairs.CopyingFolderFormat"] = "Copia cartella… ({0} file)",
    };
}
